[0m16:57:16.585861 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105eed1f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f834c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f832e0>]}


============================== 16:57:16.591694 | fd1b3f90-6f78-43d6-99bc-e62e134c929f ==============================
[0m16:57:16.591694 [info ] [MainThread]: Running with dbt=1.11.0-b3
[0m16:57:16.592143 [debug] [MainThread]: running dbt with arguments {'log_format': 'default', 'static_parser': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'log_path': 'logs', 'quiet': 'False', 'log_cache_events': 'False', 'invocation_command': 'dbt init youtube_analytics', 'partial_parse': 'True', 'empty': 'None', 'warn_error': 'None', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'profiles_dir': '/Users/williswelcome/.dbt', 'use_experimental_parser': 'False', 'write_json': 'True', 'use_colors': 'True', 'printer_width': '80', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'debug': 'False', 'version_check': 'True', 'cache_selected_only': 'False', 'introspect': 'True', 'fail_fast': 'False'}
[0m16:57:16.603340 [info ] [MainThread]: Creating dbt configuration folder at /Users/williswelcome/.dbt
[0m16:57:16.604629 [debug] [MainThread]: Starter project path: /Users/williswelcome/Library/Python/3.9/lib/python/site-packages/dbt/include/starter_project
[0m16:57:16.609496 [info ] [MainThread]: 
Your new dbt project "youtube_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:57:16.610016 [info ] [MainThread]: Setting up your profile.
[0m16:58:43.922462 [error] [MainThread]: Encountered an error:
list index out of range
[0m16:58:43.945375 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/williswelcome/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/williswelcome/Library/Python/3.9/lib/python/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/Users/williswelcome/Library/Python/3.9/lib/python/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
  File "/Users/williswelcome/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/williswelcome/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 261, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/Users/williswelcome/Library/Python/3.9/lib/python/site-packages/dbt/task/init.py", line 243, in ask_for_adapter_choice
    return available_adapters[numeric_choice - 1]
IndexError: list index out of range

[0m16:58:43.948726 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 87.41419, "process_in_blocks": "0", "process_kernel_time": 0.176671, "process_mem_max_rss": "96862208", "process_out_blocks": "0", "process_user_time": 0.82223}
[0m16:58:43.949500 [debug] [MainThread]: Command `dbt init` failed at 16:58:43.949290 after 87.42 seconds
[0m16:58:43.949873 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105eed1f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fb1160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fb1670>]}
[0m16:58:43.950190 [debug] [MainThread]: Flushing usage events
[0m16:59:43.976776 [debug] [MainThread]: An error was encountered while trying to flush usage events
